### ISSUE TITLE
Question: Buffers

### ISSUE THREAD

**Issue by Benoss** [jedisct1/flowgger#15]
> If the buffer ever gets full, new messages will not be discarded: clients simply won't be able to push new messages until the queue drains.

How is this working with the UDP input?

Other question,
Would it be possible to add a file_buffer instead of memory buffer?

Even better would be a secondary buffer, ex:
main_buffer_type=memory
main_buffer_max_message=5000
secondary_buffer_type=file
secondary_buffer_path=/tmp/flowgger.buffer
secondary_buffer_max_size=5G

Then when the output comes back online Flowgger can dump the 5gig of messages :)

**Comment by crisidev** [comment]
We restarted active development of Flowgger recently and we improved the UDP and Syslog input. Is this something still needed?

**Comment by Benoss** [comment]
Not really, I am not using file logs in any project anymore
