### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by crisidev** [jedisct1/flowgger#32]
Is there any plan to publish this package into crates.io to allow a simple `cargo install` and allow a better distribution model instead of cloning / building?

**Comment by jedisct1** [comment]
Absolutely not.

**Comment by crisidev** [comment]
Is it possible to understand the reasons behind "Absolutely not"?

**Comment by jedisct1** [comment]
Unfortunately, I don't have much spare time to work on Flowgger any more :(

**Comment by crisidev** [comment]
Sorry to hear that. Are you in any way open for contributions?

**Comment by Trojan295** [comment]
Maybe it would be also worth to publish binaries as a release in GitHub? It could be automated in Travis CI, when running a job from a semver tag

**Comment by vche** [comment]
I ilke the idea. I'll look into it, unless you want to work on that ?

**Comment by Trojan295** [comment]
I'll try figure something out on my fork. At the end most probably you will need to add some API keys to Travis CI and merge the updated Travis job in.

**Comment by vche** [comment]
No problem !

**Comment by vche** [comment]
Github bot account added to the repo for publishing releases, and travis updated

**Comment by vche** [comment]
https://crates.io/crates/flowgger
