### ISSUE TITLE
Add timestamps

### ISSUE THREAD

**Issue by peterwa88** [jedisct1/flowgger#77]
How can I add timestamp into each forwarded message in flowgger?

**Comment by peterwa88** [comment]
The following configuration does not work.

[input]
type = "tcp"                 ----->input message can be any type, I just want to add timestamp to each receive data package.
listen = "127.0.0.1:22"
framing = "line"

[output]
type = "stdout"
match = "*"
format = "json"
add_timestamp = true

**Comment by vche** [comment]
Hi ! Yes, yes, please  [check the documentation](https://github.com/awslabs/flowgger/wiki/Configuration), and use [the syslog_prepend_timestamp option](https://github.com/awslabs/flowgger/blob/master/flowgger.toml#L162).
