### ISSUE TITLE
milliseconds resolution in Gelf Decoder. 

### ISSUE THREAD

**Issue by jehuty0shift** [jedisct1/flowgger#8]
We would like to be able to send up to milliseconds resolution message in gelf_decoder.rs since it is supported by Graylog. Is it possible ? (I know the answer since the patch does not seem too big :-)

**Comment by jedisct1** [comment]
This requires an update to all the decoders and encoders, and that will be a breaking change for capnp.

But that remains fairly easy to do and the changes can definitely be made.

**Comment by jedisct1** [comment]
Finally done, although this still requires testing and a documentation update.

Please note that this is a breaking change for CapnProto users, although backward compatibility can be added if needed.

Version 0.2.0 should be tagged in the next few days.
